name: Build Plugin ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create plugin folder
        run: |
          mkdir tip-product-countdown
          rsync -av --exclude='.git' --exclude='.github' --exclude='*.md' ./ tip-product-countdown/

      - name: Create ZIP
        run: |
          zip -r tip-product-countdown.zip tip-product-countdown

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: tip-product-countdown.zip
